# ----------------------------
# This file should be called not as a part of project, but as a standalone CMake script.
# i.e. "cmake -D INPUT_FILE=<your_file_here> -P FormatCompileCommands.cmake"
#
# <your_file_here> should point to compile_commands.json, generated by your project's generator
#
# This script applies lower case to all drive letters (C:/) in this file, to work around these issues of clangd:
# https://github.com/clangd/vscode-clangd/issues/687#issuecomment-2365439284
# https://github.com/clangd/clangd/issues/108
#
# When issues above will be fixed, this workaround should be deleted.
# ----------------------------

file(READ "${INPUT_FILE}" json_data)
string(REPLACE "C:" "c:" json_data "${json_data}")
# string(REPLACE "D:" "d:" json_data "${json_data}") # choose right option lmao
# string(REPLACE "E:" "e:" json_data "${json_data}")
file(WRITE "${INPUT_FILE}" "${json_data}")
